name: dnaweaver_synbiocad
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - biopython
  - proglog
  - networkx
  - flametree
  - bioconda::dna_features_viewer
  - weasyprint
  - pandas
  - jinja2
  - dnaweaver
  - docopt
  - requests
  - openpyxl